version: '3'
services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181"
  mongo:
    image: mongo


  kafka:
    build: .
    ports:
      - "9092"
    links:
    - zookeeper

    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock`
